// Generated by SSC Studio. Edit .ssc-studio/content.json through Studio.
package net.onixary.shapeShifterCurseFabric.studio;
import net.minecraft.util.Identifier;
import net.minecraft.text.Text;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.onixary.shapeShifterCurseFabric.perk.*;
import net.onixary.shapeShifterCurseFabric.player_form.*;
public final class StudioGenerated {
  public static void register() {
    RegPerks.registerPerkCommon(new NormalPerk(new Identifier("shape-shifter-curse:snowfox_root")).setName(Text.literal("snowfox_root")).setDesc(Text.literal("")).setIcon(new Identifier("shape-shifter-curse:textures/perk/fallback.png")).XpCost(0).addPower().removePower());
    PerkTree tree0 = new PerkTree(new Identifier("shape-shifter-curse:f_snowfox_tree"));
    tree0.addNode(new Identifier("shape-shifter-curse:snowfox_root"), 0, 0);
    RegPerks.registerPerkTree(tree0);
  }
}
